### ISSUE TITLE
Display warning if access to localStorage is denied because cookies are disabled.

### ISSUE THREAD

**Issue by olberger** [deiu/solid-plume#2]
Hi.

Browsing https://deiu.me/blog/?view=https%3A%2F%2Fdeiu.me%2Fblog%2Fposts%2Fsolid-an-introduction under iceweasel (Firefox for Debian testing) doesn't render the blog post. All I see is the plume container.

The console tells me:

SecurityError: The operation is insecure.
var data = JSON.parse(localStorage.getItem(appURL));

Maybe I have tuned things too much... any suggestion ?

**Comment by olberger** [comment]
I may have been hit by https://bugzilla.mozilla.org/show_bug.cgi?id=748620 . Hth

**Comment by deiu** [comment]
It turns out that access to localStorage is not allowed in Firefox, if Cookies are disabled: https://stackoverflow.com/questions/12805487/solution-for-firefox-user-disabling-cookies-and-thus-localstorage-polyfill-not

**Comment by olberger** [comment]
Would it be possible to add an exception in the app's code that could display a warning, in case (localstorage needed and/or cookies allowed) ?

**Comment by deiu** [comment]
Yes, absolutely. I'll rename the issue to reflect this.

**Comment by olberger** [comment]
Thx

**Comment by deiu** [comment]
Fixed in 62e2d6b1ad3994cbc68742598a679608af13d875

Will also add a UI warning to let users know they won't be able to use features that depend on localStorage.
